### ISSUE TITLE
Support for class and name options

### ISSUE THREAD

**Issue by melish** [return42/linuxdoc#10]
It would be nice for flat-tables to allow the common options `class` and `name`, like the standard [list-table](https://docutils.sourceforge.io/docs/ref/rst/directives.html#list-table)

**Comment by return42** [comment]
@melish sorry for the late response / can you please confirm that the fix from https://github.com/return42/linuxdoc/pull/12 works for you / thanks!

**Comment by melish** [comment]
Confirmed, thank you.
