### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by not-my-profile** [return42/linuxdoc#15]
I'd like to use the `class` option introduced in  #12 in a project that doesn't have any bleeding edge dependencies.

I also think that the documentation should mention that `class` and `name` are only supported since version X. (I just spend way too much time trying to figure out why `class` wasn't working).

**Comment by return42** [comment]
Thanks for your reminder .. in https://github.com/return42/linuxdoc/pull/16 version [20211220](https://github.com/return42/linuxdoc/releases/tag/20211220) has been released oat https://pypi.org/project/linuxdoc/

> I also think that the documentation should mention that ...

Sorry, but I do not want to document several issues / I think github issue tracker is a good place to search for known/fixed issues: [class name](https://github.com/return42/linuxdoc/search?q=class+name&type=issues)
