### ISSUE TITLE
Struct definition and field description not showing when using typedefs

### ISSUE THREAD

**Issue by ayoubsvbri** [return42/linuxdoc#17]
Hello,

I am encountering some issues when trying to document my structs when making using of typedefs during the definition.
Let's say I have this kind of struct definition:

```c
/**
 * typedef my_struct_t - short description
 * @foo: foo
 * @bar: bar
 */
typedef struct my_struct {
    int foo;
    float bar;
} my_struct_t;
```

And in my  `doc.rst` I have the following reST directive:

```
.. kernel-doc:: my_header.h
    :symbols: my_struct_t
```

When I try this I am not getting any error and the type appears in the documentation but I am not able to display as well the structure content and the description for each field. The same issue could be applied to `enum` and all other keywords used with typedefs.
Do you have any kind of solution to be able to display as well the structure and the field descriptions?

Thank you a lot,
Ayoub

N.B.:
I'm currently using `sphinx==5.2.3`

**Comment by return42** [comment]
As far I remember, combination of typedef with structure or enum definition is not supported.

Haven't tested but this should work ..

```c

/**
 * typedef my_struct_t - typdef of &my_struct
 *
 */
typedef my_struct my_struct_t;

/**
 * struct my_struct - short description
 * @foo: foo
 * @bar: bar
 */
struct my_struct {
    int foo;
    float bar;
};
```

**Comment by ayoubsvbri** [comment]
Thank you!
