### ISSUE TITLE
Please include a license file in the sources

### ISSUE THREAD

**Issue by sanjayankur31** [return42/linuxdoc#26]
Hello!

Similar to https://github.com/return42/fspath/issues/1, could we please have a license file added here too?

Thanks very much,

**Comment by return42** [comment]
Sure, I will have a look / BTW the way I will do some clean-up

**Comment by musicinmybrain** [comment]
While GPL is not one of the licenses that *requires* the license text to be included, a license file would still be helpful.

Beyond this, the GPL is normally applied via a [license notice](https://www.gnu.org/licenses/gpl-howto.html), which GNU recommends putting in the header of each source file. Even if the notice were only in the README, it would be good to include it, and the notice would help clarify whether the intended license is [`GPL-2.0-only`](https://spdx.org/licenses/GPL-2.0-only.html) or [`GPL-2.0-or-later`](https://spdx.org/licenses/GPL-2.0-or-later.html).

You might also consider upgrading the [deprecated SPDX identifier `GPL-2.0`](https://spdx.org/licenses/GPL-2.0) in the file headers to—I assume—[`GPL-2.0-only`](https://spdx.org/licenses/GPL-2.0-only.html).

Thanks for having a look at this!

**Comment by return42** [comment]
In 95b4dea18 I switched lic to AGPLv3+, added LIC file, fixed the SPDX tags (to AGPL-3.0-or-later) and released tag [20230321](https://github.com/return42/linuxdoc/releases/tag/20230321) on pypi --> https://pypi.org/project/linuxdoc/20230321/

@sanjayankur31 I hope I have thought of everything, if I have forgotten something, please let me know. Otherwise close the ticket / Thank you! :-+1:

**Comment by return42** [comment]
OK, thanks for your feedback / I'm going to close this issue.

----

About man pages:IMO we should add man pages for the entry points (commands) here in the project.

https://github.com/return42/linuxdoc/blob/fd2f8ef6064a569ec00879236d48e74892c68786/linuxdoc/__pkginfo__.py#L115-L123

Would you like to open a new issue (or PR if you have) / thanks!
