### ISSUE TITLE
Installation of linuxdoc breaks linting local tests folder

### ISSUE THREAD

**Issue by HeinischValentin** [return42/linuxdoc#34]
Hi,

I stumbled upon a very strange behavior of pylint after installing this package.
We have got a project, that uses sphinx to create documentation and want to use the flat-table directive from the linuxdoc package.
I created a PR adding the library as a dependency. The only change is that I have added linuxdoc to the pyproject.toml.
After that, pylint started reporting the following error (when trying to lint our tests repository, containing tests for our project):
![pylint_error](https://github.com/return42/linuxdoc/assets/63716526/e5df23e4-31cb-4e63-a4b2-2f6578b1ef0d)

After some research, I noticed that after installing linuxdoc, a folder "tests" is located under "{venv}/Lib/site-packages/tests".
Removing this folder solves the issue.
The behavior could be reproduced both on windows and on linux.

I am not an expert when it comes to python packaging, so I don't know if I'm missing something, but my assumption would be, that there should not be a "tests" folder inside the site-packages directory.

BR,
Valentin

**Comment by return42** [comment]
May a exclude of the test folder is missed here:

https://github.com/return42/linuxdoc/blob/de82eeaf3e798fb0a108f2b9005953edc0af6005/setup.py#L44

.. I will have a look .. thanks for pointing out :+1:

**Comment by return42** [comment]
@HeinischValentin issue is fixed in linuxdoc-20231020

**Comment by HeinischValentin** [comment]
Thanks! 👍
