### ISSUE TITLE
Having a function with the same name as an enum or a struct makes a collision

### ISSUE THREAD

**Issue by schodet** [return42/linuxdoc#7]
First of all, thank you for this project, it makes using the kernel-doc format much simpler and the output format is nicer than with the kernel-doc script.

Now my problem:

If I define an enum (or a struct) and a fonction with the same name:

```c
/**
 * enum foo - Foo enum.
 */
enum foo
{
};

/**
 * foo() - Foo function.
 *
 * Can I reference foo() and &enum foo?
 */
void foo(void);
```

It produce the warnings:

```
.../foo.h:6: [kernel-doc WARN] : Enum value '' not described in enum 'foo'
.../foo.h:13: [kernel-doc ERROR] : name 'foo' used several times
.../foo.h:13: [kernel-doc ERROR] : name 'foo' used several times

.../foo.h:10: WARNING: Duplicate explicit target name: "foo".
```

And of course, the references do not work.

Can this be fixed or is it something sphinx is doing?

I use sphinx 2.4.4 and linuxdoc 20210110.

Thanks.

**Comment by return42** [comment]
Name collisions in headers are evil / kernel-doc (and sphinx) can't handle name collisions.

**Comment by schodet** [comment]
OK, thanks for your response.
